### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ate47** [Jake-NotTheMuss/hksc#1]
Hello,

In the repository you only have what it seems to be a file describing Lua in general (COPYRIGHT file), but nothing about this code in particular. For me it's an issue because I've slightly replaced some part to allow the compilation to the bo4 format with the xhash and I would like to share it compiled. Without a clear license it's not possible.

My goal would be to either have a compiled version available somewhere or to integrate it inside the Shield client (a bo4 client) with the code I'm writing for it. ([available here](https://github.com/ate47/shield-development/tree/dev_lua))

For now I can't propose my changes to this repository because it's fast changes I've made to quickly see the lua. For example I don't use symbols and in the code I write Engine\[@"PrintError"\](0, "...."); to write in the logs, so not acceptable for a production code.

**Comment by Jake-NotTheMuss** [comment]
I updated COPYRIGHT. Should be good now.

**Comment by ate47** [comment]
Thanks, it’s perfect.
